print('This is my first GIT Project')
print('I am learning GIT and GITHUB')
print('I am enjoying it')
print('There was no many things to learn')
print('Updating the file again as required in the question')